# Strings should be enclosed in double quotes: "..."
# Supported variables are %player%, %displayname%, %version%, and %server%
# \n can be used as a line break

# The string to send to ops when a player joins
notify-string: "&6Player &c%player% &6is using version &c%version%"

# Warn players when they have a mismatched version 
warn-players: true
warn-string: "&cNOTICE: You are running Minecraft version &e%version%\n&cThe recommended version for this server is &a%server%"

# Run at the highest priority (MONITOR)
# Set to true if %displayname% doesn't work as expected
high-priority: false
