# Strings should be enclosed in doublt quotes: "..."
# Supported variables are %player%, %version%, and %server%
# \n can be used as a line break

# The string to send to ops when a player joins
notify-string: "&6Player &c%player% &6is using version &c%version%"

# Warn players when they have a mismatched version 
warn-players: true
warn-string: "&cNOTICE: You are running Minecraft version &e%version%\n&cThe recommended version for this server is &a%server%"
